version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: expenses
  MYSQL_ROOT_PASSWORD: root

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    ports:
      - '3306:3306'
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql_db
