version: "3.8"

x-common-variables: &common-variables
    MYSQL_DATABASE: expenses
    MYSQL_ROOT_PASSWORD: root

services:
    mysql_db:
        image: mysql
        restart: always
        cap_add:
            - SYS_NICE
        volumes:
            - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
        ports:
            - "3306:3306"
        environment:
            <<: *common-variables
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: localhost

    api:
        build:
            dockerfile: Dockerfile
            context: "./"
        depends_on:
            - mysql_db
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - "5000:5000"
        environment:
            <<: *common-variables
            MYSQL_HOST_IP: mysql_db

    client:
        build:
            dockerfile: Dockerfile
            context: "./client"
        depends_on:
            - mysql_db
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            <<: *common-variables
            CHOKIDAR_USEPOLLING: true

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        depends_on:
            - mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: mysql_db
            UPLOAD_LIMIT: 300M
